---
repos:
  - repo: https://github.com/siderolabs/conform
    rev: v0.1.0-alpha.27
    hooks:
      - id: conform
        entry: 'conform enforce --commit-ref refs/remotes/origin/main --commit-msg-file'
        stages:
          - commit-msg
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.31.0
    hooks:
      - id: yamllint
        args: ['-c', '.yamllint-config.yaml']
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: pretty-format-json
        args: ['--autofix']
      - id: check-merge-conflict
      - id: check-executables-have-shebangs
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.79.1
    hooks:
      - id: terraform_fmt
      - id: terraform_tflint
        args:
          - '--args=--config=__GIT_WORKING_DIR__.tflint.hcl'
      - id: terraform_docs
