version: "3"

tasks:
  go:build:
    deps: [go:test]
    dir: src
    vars:
      OUTPUT_PATH: ./bin/bootstrap
    env:
      GOOS: linux
      GOARCH: amd64
      CGO_ENABLED: 0
    sources:
      - ./**/*.go
    generates:
      - "{{ .OUTPUT_PATH }}"
    cmds:
      - go build -o {{ .OUTPUT_PATH }}

  go:cover:
    dir: src
    cmds:
      - go test -v ./... -coverprofile=coverage.out
      - go tool cover -html=coverage.out

  go:test:
    dir: src
    sources:
      - ./**/*.go
    generates:
      - "{{ .OUTPUT_PATH }}"
    vars:
      OUTPUT_PATH: coverage.out
    cmds:
      - go mod tidy
      - go test -v ./... -coverprofile={{ .OUTPUT_PATH }}
      - go tool cover -func {{ .OUTPUT_PATH }} | grep -F total | awk '{ if ($3 < 90.0) exit 1; else exit 0 }'

  tf:apply:
    deps: [go:build]
    dir: terraform
    cmds:
      - terraform apply

  sam:local:
    deps: [go:build]
    cmds:
      - sam local invoke --event ./events/event.json
